# Generated by Django 3.0.5 on 2020-04-10 01:16

from django.db import migrations, models
import django.db.models.deletion
import employeesmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Latitude', models.FloatField(null=True)),
                ('Longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Department', to='employeesmanagement.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Image',
            field=models.ImageField(upload_to=employeesmanagement.models.upload_to_profile),
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Encoding', models.TextField(blank=True, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeesmanagement.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeIn', models.DateTimeField(blank=True, null=True)),
                ('TimeOut', models.DateField(blank=True, null=True)),
                ('Imgin', models.ImageField(blank=True, null=True, upload_to=employeesmanagement.models.upload_to_attendance)),
                ('Imgout', models.ImageField(blank=True, null=True, upload_to=employeesmanagement.models.upload_to_attendance)),
                ('Status', models.CharField(choices=[('Checked in', 'Checked in'), ('Checked out', 'Checked out')], default='Enable', max_length=15)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeesmanagement.Employee')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employeesmanagement.Location')),
            ],
        ),
    ]
