# Generated by Django 3.0.5 on 2020-04-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesmanagement', '0002_auto_20200410_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='TimeOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
