# Generated by Django 3.0.5 on 2020-04-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeesmanagement', '0006_auto_20200414_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='Employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeesmanagement.Employee'),
        ),
    ]
